### ISSUE TITLE
Korrigera referenser till streckkoder

### ISSUE THREAD

**Issue by StaffanGS1** [SwedishPaymentAndECRGroup/digital-receipt-standard#7]
Föreslår förändring av dokumentet ARTS DR version 200 with swedish extension.

Under rubriken ReceiptNumber står 

”If the receipt number TypeCode identifies a barcode, the barcode can be displayed on the digital receipt. The supported formats are Interleaved2Of5, EAN13, EAN8, Codabar, Code39, Code128, PDF417, UPC-A, UPC-E.
Example:
<ReceiptNumber TypeCode="EAN13">5060033952504</ReceiptNumber>”

Detta beskriver en användning av streckkoder i strid med de några av standarderna för dess. Föreslår att texten ändras till:

”If the receipt number TypeCode identifies a barcode, the barcode can be displayed on the digital receipt. The supported formats are Interleaved2Of5, , Codabar, Code39, Code128, PDF417, QR and Data Matrix.
Example:
<ReceiptNumber TypeCode="Code39">AEXD5039G2504</ReceiptNumber>”

Bakgrund till förändringsförslag:
1.	De 4 GS1-streckkoder som nämns i listan (EAN13, EAN8, UPC-A och UPC-E) är i grundstandarden avgränsad till att bära GS1 artikelnummer (GTIN). Det är alltså inte möjligt att följa ISO-standarden för dessa streckkodstyper och lägga in ett kvittonummer. En scannerutrustning som scannar detta kommer att anta att den scannar en artikel. Inte ett kvitto.

2.	Streckkodstypslistan bör kompletteras med QR och Data Matrix, då det är de streckkoder som sprids snabbast för denna typ av tillämpningar.

3.	Exemplet bör ändras. Dels till annan streckkodstyp (se ovan), och dels till ett nummer som inte ser ut som ett GTIN (eftersom det har TypeCode=EAN13, giltig GTIN-längd och korrekt checksiffra). Just i detta fall är exemplet dessutom ett GTIN som är licensierat till en betalande GS1-kund (i UK). Prova att söka efter GTIN 5060033952504 i GS1s nummerupplysning  http://www.gs1.se/sv/Support/Nummerupplysning/

Staffan Olsson, GS1 Sweden

**Comment by larsbstrom** [comment]
Tack för informationen Staffan. Anledningen att streckkodstyperna finns med är att ARTS har lagt in dem som godkända typer för bl a ReceiptNumber vilket ju är olyckligt med tanke på det du skriver.

Lägger gärna till QR och Data Matrix. Frågan är om vi ska göra det som en ARTS-extension, dvs ARTS tillåter andra typer än de som de räknar upp men då måste dom prefixas med något. T ex "SE:QS".

Alternativet är att lägga till ett "eget ReceiptNumber" i det svenska schemat med stöd för de typer som du nämner.

**Comment by StaffanGS1** [comment]
Jag anade att detta följt med från ARTS. Jag har ingen särskild åsikt om vad den bästa lösningen. I den ideala världen gör man en Work Request till OMG att korrigera och komplettera listan, men det är ju inte i detta projekts scope. Enklast är nog att lägga till QR och Data Matrix med ett prefix på något sätt som du föreslår. Parallellt kommer jag försöka få någon inom GS1 att föreslå OMG en uppdatering till kommande ARTS-versioner.
